// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void play(
    ffi.Pointer<ffi.Int8> url,
  ) {
    return _play(
      url,
    );
  }

  late final _play_ptr = _lookup<ffi.NativeFunction<_c_play>>('play');
  late final _dart_play _play = _play_ptr.asFunction<_dart_play>();

  ffi.Pointer<ffi.Int8> getFFmpegVersion() {
    return _getFFmpegVersion();
  }

  late final _getFFmpegVersion_ptr =
      _lookup<ffi.NativeFunction<_c_getFFmpegVersion>>('getFFmpegVersion');
  late final _dart_getFFmpegVersion _getFFmpegVersion =
      _getFFmpegVersion_ptr.asFunction<_dart_getFFmpegVersion>();
}

typedef _c_play = ffi.Void Function(
  ffi.Pointer<ffi.Int8> url,
);

typedef _dart_play = void Function(
  ffi.Pointer<ffi.Int8> url,
);

typedef _c_getFFmpegVersion = ffi.Pointer<ffi.Int8> Function();

typedef _dart_getFFmpegVersion = ffi.Pointer<ffi.Int8> Function();
